#!/usr/bin/env bash
#
# Generates every secret docker-compose.prod.example.yml needs, into an env file the
# compose stack reads with `env_file:`.
#
#   ./generate-secrets.sh                    # writes ./worklogd.prod.env
#   ./generate-secrets.sh --force            # overwrite an existing file
#   ./generate-secrets.sh /srv/worklogd.env # write somewhere else
#
# Everything here is generated locally with openssl - nothing needs the app, PHP, a
# database or a running container. What it cannot generate is the credentials of other
# people's systems: MAIL_USERNAME / MAIL_PASSWORD and, if you want the Google Calendar
# integration, GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET. Those stay in the compose file.
#
# One follow-up step remains, and it is printed at the end: the first user. Self-hosted
# installs have no public sign-up, so a fresh database has no accounts and nothing can
# log in until `php artisan admin:user:create` has run.
#
# Nothing here covers the personal access client the API token screen mints tokens
# through. Passport 13 finds it by querying oauth_clients rather than by configured id
# and secret, so the app containers create the row themselves on boot.
#
# Do not regenerate this file for an existing installation:
#   APP_KEY      decrypts every stored Jira and Google token - changing it orphans them.
#   PASSPORT_*   keys sign every API token - changing them logs out every API client
#                and the desktop/mobile apps.
#   DB_PASSWORD  is baked into the postgres volume on first boot; changing it here
#                without an ALTER ROLE leaves the app unable to connect.

set -euo pipefail

readonly OUTPUT_DEFAULT='worklogd.prod.env'

force=false
output=''

while [ $# -gt 0 ]; do
    case "$1" in
        -f | --force)
            force=true
            ;;
        -h | --help)
            sed -n '2,28p' "$0" | cut -c 3-
            exit 0
            ;;
        -*)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
        *)
            if [ -n "$output" ]; then
                echo "Only one output path may be given." >&2
                exit 1
            fi
            output="$1"
            ;;
    esac
    shift
done

output="${output:-$OUTPUT_DEFAULT}"

if ! command -v openssl > /dev/null 2>&1; then
    echo "openssl is required and was not found in PATH." >&2
    exit 1
fi

if [ -e "$output" ] && [ "$force" != true ]; then
    echo "$output already exists. Pass --force to overwrite it - but read the warning" >&2
    echo "at the top of this script first: for an installation that is already running," >&2
    echo "new secrets mean lost tokens and an unreachable database." >&2
    exit 1
fi

# Alphanumeric only. These end up in a postgres role password and a URL-ish client
# secret, so anything that needs escaping somewhere is more trouble than the entropy
# it buys. 40 characters of [A-Za-z0-9] is ~238 bits.
random_alnum() {
    local length="$1"
    # base64 of 2x the bytes leaves plenty of material after the non-alphanumerics
    # are stripped, and openssl's output is finite so nothing here can SIGPIPE.
    openssl rand -base64 "$((length * 2))" | tr -dc 'A-Za-z0-9' | cut -c "1-${length}"
}

# Compose expands \n inside a double quoted env_file value into a real newline, so the
# PEM arrives in the container intact. Passport also un-escapes literal \n itself, so
# this survives either way - including being pasted straight into a .env file.
pem_to_single_line() {
    awk '{ printf "%s\\n", $0 }' "$1"
}

keydir="$(mktemp -d)"
trap 'rm -rf "$keydir"' EXIT
chmod 700 "$keydir"

# 4096-bit RSA, matching what `php artisan passport:keys` produces. openssl writes
# PKCS#8 where passport writes PKCS#1; both are read by the same openssl underneath.
openssl genpkey -quiet -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out "$keydir/oauth-private.key"
openssl rsa -in "$keydir/oauth-private.key" -pubout -out "$keydir/oauth-public.key" 2> /dev/null

app_key="base64:$(openssl rand -base64 32)"
db_password="$(random_alnum 40)"
passport_private_key="$(pem_to_single_line "$keydir/oauth-private.key")"
passport_public_key="$(pem_to_single_line "$keydir/oauth-public.key")"

# 077 so the file is 0600 from the moment it exists, rather than briefly world readable.
(
    umask 077
    cat > "$output" <<EOF
# Generated by generate-secrets.sh. Keep this file, back it up, and do not commit it.
#
# Losing it is not recoverable by regenerating: APP_KEY decrypts the stored Jira and
# Google credentials, and the passport keys sign every API token in circulation.

# php artisan key:generate --show
APP_KEY="${app_key}"

# The app connects with DB_PASSWORD; postgres creates the role from POSTGRES_PASSWORD
# on first boot. They have to match, so both are written here from one value.
DB_PASSWORD="${db_password}"
POSTGRES_PASSWORD="${db_password}"

# php artisan passport:keys, as single line PEMs. Identical across every container.
PASSPORT_PRIVATE_KEY="${passport_private_key}"
PASSPORT_PUBLIC_KEY="${passport_public_key}"
EOF
)

cat <<EOF
Wrote $output (mode $(stat -c '%a' "$output" 2> /dev/null || stat -f '%Lp' "$output")).

Still to fill in by hand, in docker-compose.prod.yml - nothing can generate them:

    APP_URL, SUPER_ADMINS
    MAIL_HOST / MAIL_USERNAME / MAIL_PASSWORD / MAIL_FROM_ADDRESS
    GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET   (only if you want Google Calendar)

Then bring the stack up. The app container migrates the database, creates the storage
directories and creates the personal access client the API token screen needs, all on
boot - none of it needs running by hand:

    docker compose -f docker-compose.prod.yml up -d

One thing is left. Create the first user: there is no sign-up on a self-hosted install -
APP_ENABLE_REGISTRATION is off in the example stack, so the database starts empty and
nothing can log in until this has run:

    docker compose -f docker-compose.prod.yml exec app \\
        php artisan admin:user:create "Your Name" you@example.com --verify-email

It prints a generated password, and creates the user's personal organization along
with them. Use the address you put in SUPER_ADMINS and keep --verify-email: admin
panel access needs the email both listed there and verified. Everyone after the first
user joins by invitation, so registration can stay off.
EOF
